config/routes.rb
Rails.application.routes.draw do
  resources :contatos
  root :to =>"contatos#index"
  get "/index" =>"contatos#index"
  post "/resultado" => "contatos#resultado"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contato.rb
class Contato < ApplicationRecord
  validates_presence_of:nome
  validates_presence_of:telefone
  def self.search(query)
		where("nome LIKE :q", :q => "%#{query}%")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all
  end

  def resultado
    @contatos = Contato.search(params[:query])
    respond_with = @contatos
  end
  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato criado com sucesso!.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato alterado com sucesso!.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato excluido com sucesso!.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :email, :telefone, :endereco, :detalhes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/views/contatos/_form.html.erb
<%= form_for(contato) do |f| %>
  <% if contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contato.errors.count, "error") %> ao salvar Contato!:</h2>

      <ul>
      <% contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :telefone %>
    <%= f.text_field :telefone %>
  </div>

  <div class="field">
    <%= f.label :endereco %>
    <%= f.text_field :endereco %>
  </div>
<div class="det">
  <div class="field">
    <%= f.label :detalhes %>
    <%= f.text_area :detalhes %>
  </div>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contatos/edit.html.erb
<h1>Alterar Contato</h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Exibir', @contato %> |
<%= link_to 'Voltar', contatos_path %>

app/views/contatos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="titulo"><h1>Contatos</h1></div>
<div class="pesquisa">
    <%= form_tag resultado_path, :method =>'post' do %>
    <%= text_field_tag :query, params[:query]%>
    <%= submit_tag "Procurar", :nome => nil %>
    <%end%>
</div>
<div class="tabela">
<table cellspacing="0">
    <div class="bgti"</div>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Endereco</th>
      <th>Detalhes</th>
      <th colspan="3"></th>
    </tr>
  </thead>
</div>
</div>
  <tbody>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.nome %></td>
        <td><%= contato.email %></td>
        <td><%= contato.telefone %></td>
        <td><%= contato.endereco %></td>
        <td><%= contato.detalhes %></td>
        <td><%= link_to 'Exibir', contato %></td>
        <td><%= link_to 'Alterar', edit_contato_path(contato) %></td>
        <td><%= link_to 'Excluir', contato, method: :delete, data: { confirm: 'Esta certo disso?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Contato', new_contato_path %>

app/views/contatos/new.html.erb
<h1>Novo Contato</h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Voltar', contatos_path %>

app/views/contatos/resultado.html.erb
<h3> Resultado da pesquisa</h3>

<tbody>
	<% @contatos.each do |contato| #for enquanto tiver produtos<%>
<tr>
		<td>Nome: <%= contato.nome %></td>
	<td>  </td>
		<td> Email: <%= contato.email %></td>
	</tr>
</br>
	<% end %>
</tbody>
</br>
<td><%= link_to 'Voltar',"contatos" %></td>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contato.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contato.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @contato.telefone %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @contato.endereco %>
</p>

<p>
  <strong>Detalhes:</strong>
  <%= @contato.detalhes %>
</p>

<%= link_to 'Alterar', edit_contato_path(@contato) %> |
<%= link_to 'Voltar', contatos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>